name: Deploy Portfolio

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository # ขั้นตอนที่ 1: ดึงโค้ดจาก repository
        uses: actions/checkout@v4 # ใช้ actions/checkout@v4

      - name: Deploy to GitHub Pages # ขั้นตอนที่ 2: Deploy
        uses: peaceiris/actions-gh-pages@v4 # ใช้ peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # ตรวจสอบให้แน่ใจว่า "./" ชี้ไปที่โฟลเดอร์ที่ถูกต้อง
          force_orphan: true # ใส่กลับคืนมาเพื่อให้ deploy สะอาด
          # cname: your-domain.com
          # destination_dir: docs
