name: Deploy Portfolio

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # เพิ่มขั้นตอนใหม่นี้เข้าไป (สำคัญ!)
      - name: Setup Git for Deployment
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # ตรวจสอบว่า gh-pages branch มีอยู่หรือไม่ ถ้าไม่มี ให้สร้าง
          git checkout gh-pages || git checkout -b gh-pages
          git branch -M gh-pages # ตรวจสอบให้แน่ใจว่าชื่อ branch เป็น gh-pages

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          force_orphan: true
          # cname: your-domain.com
          # destination_dir: docs
