- name: Test for required files
  run: |
    if [ ! -f index.html ]; then echo "❌ index.html ไม่พบ"; exit 1; fi
    if [ ! -f style.css ]; then echo "❌ style.css ไม่พบ"; exit 1; fi
    echo "✅ ไฟล์อยู่ครบทั้งหมด!"
